<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Fluid.Core" Version="2.31.0" />
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="MassTransit" Version="8.5.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="8.0.0" />
    <PackageReference Include="Npgsql" Version="8.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ItConsultations.Business\ItConsultations.Business.csproj" />
	<ProjectReference Include="..\ItConsultations.DataAccess\ItConsultations.DataAccess.csproj" />
	<ProjectReference Include="..\ItConsultations.Logger\ItConsultations.Logger.csproj" />
  </ItemGroup>
</Project>
